spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 892205532295-j15ge9fpqmt6289c397fkar63und8ec1.apps.googleusercontent.com
            clientSecret: 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
            scope: profile, email
            redirectUri: "{baseUrl}/login/oauth2/code/{registrationId}"
            clientName: Google
          provider:
            google:
              authorizationUri: https://accounts.google.com/o/oauth2/auth
              tokenUri: https://oauth2.googleapis.com/token
              userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo